### ISSUE TITLE
Fatal Error backtrace isn't very useful in Linux

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1207]
Here is how the backtrace is presented by a Fatal Error:
```console
anon@DESKTOP-KLM29AC:~/TestFC/build/Debug_Linux64/TestFC$ ./TestFC
Fatal error encountered at line 9 in /home/anon/TestFC/src/Program.bf
**** FATAL APPLICATION ERROR ****
0x0x4256a9 ./TestFC
0x0x421649 ./TestFC
0x0x4198b2 ./TestFC
0x0x420914 ./TestFC
0x0x420a26 ./TestFC
0x0x4209fa ./TestFC
0x0x7fc387d6609b __libc_start_main
0x0x4046aa ./TestFC
```
_(Not really important, but we can also see that `0x` is duplicated)_

And here is how the backtrace is presented if you use gdb to break at the FatalError function and get a backtrace:
```console
anon@DESKTOP-KLM29AC:~/TestFC/build/Debug_Linux64/TestFC$ gdb TestFC
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.

Reading symbols from TestFC...done.
(gdb) break BfpSystem_FatalError
Breakpoint 1 at 0x425680: file /home/anon/Beef/BeefySysLib/platform/linux/../posix/PosixCommon.cpp, line 675.
(gdb) run
Starting program: /home/anon/TestFC/build/Debug_Linux64/TestFC/TestFC
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, BfpSystem_FatalError (
    error=error@entry=0x4d0ed0 "Fatal error encountered at line 9 in /home/anon/TestFC/src/Program.bf",
    title=title@entry=0x446ae9 "BEEF FATAL ERROR")
    at /home/anon/Beef/BeefySysLib/platform/linux/../posix/PosixCommon.cpp:675
675         BFP_ERRPRINTF("%s\n", error);
(gdb) bt
#0  BfpSystem_FatalError (
    error=error@entry=0x4d0ed0 "Fatal error encountered at line 9 in /home/anon/TestFC/src/Program.bf",
    title=title@entry=0x446ae9 "BEEF FATAL ERROR")
    at /home/anon/Beef/BeefySysLib/platform/linux/../posix/PosixCommon.cpp:675
#1  0x0000000000421649 in Internal_FatalError (
    error=0x4d0ed0 "Fatal error encountered at line 9 in /home/anon/TestFC/src/Program.bf")
    at /home/anon/Beef/BeefRT/rt/Internal.cpp:228
#2  0x00000000004198b2 in bf::System::Runtime::FatalError (msg=0x4b90d0 <__bfStrObj21>,
    filePath=0x4ba530 <__bfStrObj37>, line=9) at /home/anon/Beef/BeefLibs/corlib/src/Runtime.bf:306
#3  0x0000000000420914 in bf::TestFC::Program::Main (args=0x4d0e20) at /home/anon/TestFC/src/Program.bf:9
#4  0x0000000000420a26 in BeefStartProgram () at /home/anon/Beef/BeefRT/../BeefySysLib/util/String.h:1113
#5  0x00000000004209fa in main () at /home/anon/Beef/BeefRT/../BeefySysLib/util/String.h:1113
```

It would be very useful if a Fatal Error could at least show the file names like in gdb

**Comment by bfiete** [comment]
Do you have libbacktrace installed? It's supposed to give symbols if you do (you will have to rebuild Beef after installing).

**Comment by disarray2077** [comment]
I see... No, I don't have libbacktrace installed, this must be the reason :)
